### ISSUE TITLE
publish it to npm

### ISSUE THREAD

**Issue by Ghostavio** [franciscop/cookies.js#6]
bower is pretty much dying, could you also offer an npm package for this?

**Comment by ManWhoSoldthWorld** [comment]
I just found out why and by who.. Everything I have been going through.. I
don't know what that means,  what you wrote.. I do know I am going to win
and save the world.. Everyone I know doublecrossed and lied to me..
Watching me go through he'll. And all of you people did not help in one
bit.. Brandi Rawlings is a worthless whore,  and she has a severe problem.
As does your site.. Feds been investigating since May. I am going to sue
Ubuntu and Apache with everything I got.. I wish never stop.. Apache is on
the forever decline. There's a new sheriff in town,  and it's name is
Yahoo,  and Mozilla Firefox...

Otown

**Comment by ManWhoSoldthWorld** [comment]
Sorry about that.  My life had been he'll the last year and a half.. 19
months.. I have been hacked constantly. It'd been terrible.

OtownSorr

**Comment by ManWhoSoldthWorld** [comment]
And I still and always will love her.

Otown

**Comment by franciscop** [comment]
But it *is* in npm, which is a PITA since every time I publish a new version I have to remember to also `npm publish` it while bower automatically gets this from Github. You can see there is a root package.json with the name on it:

```
npm install cookiesjs
```

It also has a `module.exports = cookies;` in the code. Now it is not documented since it is not oficially supported (for the reasons stated above), but it *should work*.

**Comment by Ghostavio** [comment]
maybe you can give this a shot: https://www.npmjs.com/package/publish
